name: test
on:
  push:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: string
        default: production
permissions:
  id-token: write
  contents: write
  checks: write
  packages: write

jobs:
   matrix:
     uses: ./.github/workflows/matrix.yml
  
   deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: print
      run: |
        # Assuming 'array_string' is your JSON string
        array_str='[
                    {
                      "name": "Alice",
                      "age": 30
                    },
                    {
                      "name": "Bob",
                      "age": 25
                    },
                    {
                      "name": "Charlie",
                      "age": 35
                    }
                  ]'
        
        # Access all elements
        
        echo "$json" | jq -r '.[] |  echo "Name is \(.name), Age is \(.age)"
        echo "$array_str" | jq -r .[]

